Related to pip install flair issue
Related to flair install issue https://github.com/flairNLP/flair/issues/1327

Description
PyPI flair install is failing. When we try to install pip install flair it failed with an error message

ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
tiny-tokenizer depends on SudachiDict_core@ https://object-storage.tyo2.conoha.io/v1/nc_2520839e1f9641b08211a5c85243124a/sudachi/SudachiDict_core-20190927.tar.gz